### PR TITLE
LPIX-3215 Fixing text gravity

### PR DESCRIPTION
**Pull request by oleksii-iermolenko**
Fixing the layout gravity to match the design in Figma
photo_2021-11-03_16-26-00

### CODE REVIEW

**Review by Saravana-Gunaseelan — COMMENTED** [review]
Will this affect other screens where the text does not need to be center aligned?

**Comment by oleksii-iermolenko** [comment]
Judging by designs this tutorial is the same across the app, isn't it?

**Review by redko-o — APPROVED** [review]

**Comment by oleksii-iermolenko** [comment]
Ok, added an ability to change text gravity in the library

**Review by Saravana-Gunaseelan — APPROVED** [review]
LGTM

**Pull request merged**
